--[[
    init.lua
    Created: 06/29/2021 10:02:14
    Description: Autogenerated script file for the map guild_guildmasters_room.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'
require 'ground.guild_guildmasters_room.guild_guildmasters_room_ch_1'
require 'ground.guild_guildmasters_room.guild_guildmasters_room_ch_2'
require 'ground.guild_guildmasters_room.guild_guildmasters_room_ch_3'
require 'ground.guild_guildmasters_room.guild_guildmasters_room_ch_4'
require 'ground.guild_guildmasters_room.guild_guildmasters_room_ch_5'

-- Package name
local guild_guildmasters_room = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_guildmasters_room.Init
--Engine callback function
function guild_guildmasters_room.Init(map)
	DEBUG.EnableDbgCoro()
	print('=>> Init_guild_guildmasters_room<<=')
	MapStrings = COMMON.AutoLoadLocalizedStrings()
	COMMON.RespawnAllies()
	PartnerEssentials.InitializePartnerSpawn()
	
	--Remove nicknames from characters if the nickname mod is enabled.
	if CONFIG.UseNicknames then
		CH('Tropius').Data.Nickname = CharacterEssentials.GetCharacterName('Tropius')
	else 
		CH('Tropius').Data.Nickname = 'Tropius'
	end
end

---guild_guildmasters_room.Enter
--Engine callback function
function guild_guildmasters_room.Enter(map)
	guild_guildmasters_room.PlotScripting()
end

---guild_guildmasters_room.Exit
--Engine callback function
function guild_guildmasters_room.Exit(map)


end

---guild_guildmasters_room.Update
--Engine callback function
function guild_guildmasters_room.Update(map)


end

function guild_guildmasters_room.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	guild_guildmasters_room.PlotScripting()
end

function guild_guildmasters_room.GameSave(map)
	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))
end

function guild_guildmasters_room.PlotScripting()
	--plot scripting
	if SV.ChapterProgression.Chapter == 1 then
		if SV.Chapter1.TeamCompletedForest then 
			guild_guildmasters_room_ch_1.MeetGuildmaster()
		else
			GAME:FadeIn(20)
		end
	elseif SV.ChapterProgression.Chapter == 2 then 
		if SV.Chapter2.FinishedRiver then 
			guild_guildmasters_room_ch_2.NoctowlTropiusScene()
		else
			GAME:FadeIn(20)
		end
	elseif SV.ChapterProgression.Chapter == 4 then
		if SV.Chapter4.FinishedGrove and not SV.Chapter4.FinishedBedtimeCutscene then
			guild_guildmasters_room_ch_4.PresentApricornCutscene()
		else 
			GAME:FadeIn(20)
		end
	elseif SV.ChapterProgression.Chapter == 5 then
		guild_guildmasters_room_ch_5.SetupGround()
	else
		GAME:FadeIn(20)
	end
end

-------------------------------
-- Entities Callbacks
-------------------------------
function guild_guildmasters_room.Tropius_Action(obj, activator)
 DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("guild_guildmasters_room_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Tropius_Action(...,...)"), obj, activator))
end

function guild_guildmasters_room.Noctowl_Action(obj, activator)
 DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("guild_guildmasters_room_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Noctowl_Action(...,...)"), obj, activator))
end

function guild_guildmasters_room.Breloom_Action(obj, activator)
 DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("guild_guildmasters_room_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Breloom_Action(...,...)"), obj, activator))
end

function guild_guildmasters_room.Girafarig_Action(obj, activator)
 DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("guild_guildmasters_room_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Girafarig_Action(...,...)"), obj, activator))
end

function guild_guildmasters_room.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
end

---------------------------
-- Map Transitions
---------------------------
function guild_guildmasters_room.Bottom_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_third_floor_lobby", "Guild_Third_Floor_Lobby_Door_Marker")
  SV.partner.Spawn = 'Guild_Third_Floor_Lobby_Door_Marker_Partner'
end

return guild_guildmasters_room

