--[[
    init.lua
    Created: 12/05/2023 20:58:37
    Description: Autogenerated script file for the map mount_windswept.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local mount_windswept = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---mount_windswept.Init(zone)
--Engine callback function
function mount_windswept.Init(zone)


end

---mount_windswept.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function mount_windswept.EnterSegment(zone, rescuing, segmentID, mapID)


end

---mount_windswept.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function mount_windswept.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---mount_windswept.Rescued(zone, name, mail)
--Engine callback function
function mount_windswept.Rescued(zone, name, mail)


end

return mount_windswept

