--[[
    init.lua
    Created: 03/21/2021 22:07:39
    Description: Autogenerated script file for the map metano_grass_home.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'

-- Package name
local metano_grass_home = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---metano_grass_home.Init
--Engine callback function
function metano_grass_home.Init(map, time)

	DEBUG.EnableDbgCoro()
	print('=>> Init_metano_grass_home <<=')
	MapStrings = COMMON.AutoLoadLocalizedStrings()
	COMMON.RespawnAllies()
	

	--set partner to follow us, disable his collision
	local chara = CH('Teammate1')
	AI:SetCharacterAI(chara, "ai.ground_partner", CH('PLAYER'), chara.Position)
	chara.CollisionDisabled = true

end

---metano_grass_home.Enter
--Engine callback function
function metano_grass_home.Enter(map, time)
	DEBUG.EnableDbgCoro()
	print('Enter_metano_grass_home')
	GAME:FadeIn(20)
	UI:ResetSpeaker()

end

---metano_grass_home.Exit
--Engine callback function
function metano_grass_home.Exit(map, time)


end

---metano_grass_home.Update
--Engine callback function
function metano_grass_home.Update(map, time)


end

-------------------------------
-- Map Transitions
-------------------------------

function metano_grass_home.Grass_Home_Entrance_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("metano_town", "Grass_Home_Entrance_Marker")
  SV.partner.Spawn = 'Grass_Home_Entrance_Marker_Partner'
end



------------------
--NPCS 
----------------
function metano_grass_home.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))end

return metano_grass_home

