--[[
    init.lua
    Created: 02/06/2021 17:32:04
    Description: Autogenerated script file for the map testmap.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'

-- Package name
local testmap = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---testmap.Init
--Engine callback function
function testmap.Init(map, time)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  
  --local chara = CH('Teammate1')
	--AI:SetCharacterAI(chara, "ai.ground_partner", CH('PLAYER'), chara.Position)
   -- chara.CollisionDisabled = true
	
	GROUND:AddMapStatus(50)

end

---testmap.Enter
--Engine callback function
function testmap.Enter(map, time)


end

---testmap.Update
--Engine callback function
function testmap.Update(map, time)


end

-------------------------------
-- Entities Callbacks
-------------------------------

function testmap.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end



return testmap

