--[[
    init.lua
    Created: 09/02/2023 16:21:45
    Description: Autogenerated script file for the map trial_of_strength.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local trial_of_strength = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---trial_of_strength.Init(zone)
--Engine callback function
function trial_of_strength.Init(zone)


end

---trial_of_strength.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function trial_of_strength.EnterSegment(zone, rescuing, segmentID, mapID)


end

---trial_of_strength.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function trial_of_strength.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---trial_of_strength.Rescued(zone, name, mail)
--Engine callback function
function trial_of_strength.Rescued(zone, name, mail)


end

return trial_of_strength

