--[[
    init.lua
    Created: 12/23/2023 14:32:40
    Description: Autogenerated script file for the map searing_crucible.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'
require 'ground.searing_crucible.searing_crucible_ch_5'

-- Package name
local searing_crucible = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---searing_crucible.Init(map)
--Engine callback function
function searing_crucible.Init(map)
  DEBUG.EnableDbgCoro()
  print('=>> Init_searing_crucible <<=')
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  COMMON.RespawnAllies(true)
  GROUND:AddMapStatus("steam")
  PartnerEssentials.InitializePartnerSpawn()

end

---searing_crucible.Enter(map)
--Engine callback function
function searing_crucible.Enter(map)

  searing_crucible.PlotScripting()

end

---searing_crucible.Exit(map)
--Engine callback function
function searing_crucible.Exit(map)


end

---searing_crucible.Update(map)
--Engine callback function
function searing_crucible.Update(map)


end

---searing_crucible.GameSave(map)
--Engine callback function
function searing_crucible.GameSave(map)

	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))

end

---searing_crucible.GameLoad(map)
--Engine callback function
function searing_crucible.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	searing_crucible.PlotScripting()
end

function searing_crucible.PlotScripting()
	if SV.ChapterProgression.Chapter == 5 then
		if SV.Chapter5.DefeatedBoss then 
			GAME:FadeIn(20)
		elseif not SV.Chapter5.EncounteredBoss then
			searing_crucible_ch_5.FirstPreBossScene()
		else
			GAME:FadeIn(20)
		end
	else
		GAME:FadeIn(20)
	end
end 


-------------------------------
-- Entities Callbacks
-------------------------------
function searing_crucible.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
 end

function searing_crucible.Teammate2_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function searing_crucible.Teammate3_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

return searing_crucible

