--[[
    init.lua
    Created: 08/07/2022 23:57:58
    Description: Autogenerated script file for the map crooked_cavern_entrance.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'
require 'ground.crooked_cavern_entrance.crooked_cavern_entrance_ch_3'

-- Package name
local crooked_cavern_entrance = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---crooked_cavern_entrance.Init
--Engine callback function
function crooked_cavern_entrance.Init(map, time)

	DEBUG.EnableDbgCoro()
	print('=>> Init_crooked_cavern_entrance <<=')
	MapStrings = COMMON.AutoLoadLocalizedStrings()
	COMMON.RespawnAllies()
	PartnerEssentials.InitializePartnerSpawn()
end

---crooked_cavern_entrance.Enter
--Engine callback function
function crooked_cavern_entrance.Enter(map, time)

	crooked_cavern_entrance.PlotScripting()

end

---crooked_cavern_entrance.Exit
--Engine callback function
function crooked_cavern_entrance.Exit(map, time)


end

---crooked_cavern_entrance.Update
--Engine callback function
function crooked_cavern_entrance.Update(map, time)


end

function crooked_cavern_entrance.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	crooked_cavern_entrance.PlotScripting()
end

function crooked_cavern_entrance.GameSave(map)
	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))
end


function crooked_cavern_entrance.PlotScripting()
	if SV.ChapterProgression.Chapter == 3 then 
		if not SV.Chapter3.EnteredCavern then
			crooked_cavern_entrance_ch_3.FirstAttemptCutscene()
		elseif not SV.Chapter3.EncounteredBoss then
			crooked_cavern_entrance_ch_3.LostBeforeStyle()
		else 
			crooked_cavern_entrance_ch_3.LostToStyle()
		end
	else
		GAME:FadeIn(20)
	end
end





function crooked_cavern_entrance.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
 end

return crooked_cavern_entrance


