--[[
    init.lua
    Created: 11/07/2023 16:28:42
    Description: Autogenerated script file for the map searing_tunnel.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local searing_tunnel = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---searing_tunnel.Init(zone)
--Engine callback function
function searing_tunnel.Init(zone)


end

---searing_tunnel.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function searing_tunnel.EnterSegment(zone, rescuing, segmentID, mapID)


end

---searing_tunnel.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function searing_tunnel.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---searing_tunnel.Rescued(zone, name, mail)
--Engine callback function
function searing_tunnel.Rescued(zone, name, mail)


end

return searing_tunnel

