--[[
    init.lua
    Created: 06/30/2021 01:54:56
    Description: Autogenerated script file for the map guild_storage_hallway.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'
require 'GeneralFunctions'
require 'ground.guild_storage_hallway.guild_storage_hallway_ch_1'


-- Package name
local guild_storage_hallway = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_storage_hallway.Init
--Engine callback function
function guild_storage_hallway.Init(map)
	DEBUG.EnableDbgCoro()
	print('=>> Init_guild_storage_hallway<<=')
	MapStrings = COMMON.AutoLoadLocalizedStrings()
	COMMON.RespawnAllies()
	PartnerEssentials.InitializePartnerSpawn()


end

---guild_storage_hallway.Enter
--Engine callback function
function guild_storage_hallway.Enter(map)
	guild_storage_hallway.PlotScripting()
end

---guild_storage_hallway.Exit
--Engine callback function
function guild_storage_hallway.Exit(map)


end

---guild_storage_hallway.Update
--Engine callback function
function guild_storage_hallway.Update(map)


end

function guild_storage_hallway.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	guild_storage_hallway.PlotScripting()
end

function guild_storage_hallway.GameSave(map)
	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))
end

function guild_storage_hallway.PlotScripting()
	--plot scripting
	if SV.ChapterProgression.Chapter == 1 then
		if not SV.Chapter1.MetAudino then --bump into audino for first time if you haven't yet
			guild_storage_hallway_ch_1.MeetAudino()
		else 
			GAME:FadeIn(20)
		end
	else
		GAME:FadeIn(20)
	end
end

---------------------------------
-- Event Trigger
-- This is a temporary object created by a script used to trigger events that only happen
-- once, typically a cutscene of sorts for a particular chapter.
---------------------------------
function guild_storage_hallway.Event_Trigger_1_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("guild_storage_hallway_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Event_Trigger_1_Touch(...,...)"), obj, activator))
end






-------------------------------
-- Entities Callbacks
-------------------------------
function guild_storage_hallway.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
end

---------------------------
-- Map Transitions
---------------------------
function guild_storage_hallway.Top_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_third_floor_lobby", "Guild_Third_Floor_Lobby_Bottom_Marker")
  SV.partner.Spawn = 'Guild_Third_Floor_Lobby_Bottom_Marker_Partner'
end

function guild_storage_hallway.Right_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_storage_room", "Main_Entrance_Marker")
  SV.partner.Spawn = 'Default'
end

--you aren't allowed to go into the guildmaster's room, at least for now
function guild_storage_hallway.Left_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro()
  local partner = CH('Teammate1')
  local hero = CH('PLAYER')
  GeneralFunctions.StartPartnerConversation("H-Hey,[pause=10] that's the way to the Guildmaster's room!", "Surprised")
  UI:SetSpeakerEmotion("Worried")
  UI:WaitShowDialogue("We aren't allowed in there.[pause=0] Let's turn back before we get into any trouble.")
  GeneralFunctions.EndConversation(partner)
end

return guild_storage_hallway

