--[[
    init.lua
    Created: 06/30/2021 01:54:56
    Description: Autogenerated script file for the map guild_storage_hallway.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'

-- Package name
local guild_storage_hallway = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_storage_hallway.Init
--Engine callback function
function guild_storage_hallway.Init(map)
	DEBUG.EnableDbgCoro()
	print('=>> Init_guild_storage_hallway<<=')
	MapStrings = COMMON.AutoLoadLocalizedStrings()
	COMMON.RespawnAllies()
	PartnerEssentials.InitializePartnerSpawn()

end

---guild_storage_hallway.Enter
--Engine callback function
function guild_storage_hallway.Enter(map)

  GAME:FadeIn(20)

end

---guild_storage_hallway.Exit
--Engine callback function
function guild_storage_hallway.Exit(map)


end

---guild_storage_hallway.Update
--Engine callback function
function guild_storage_hallway.Update(map)


end

-------------------------------
-- Entities Callbacks
-------------------------------
function guild_storage_hallway.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
end

---------------------------
-- Map Transitions
---------------------------
function guild_storage_hallway.Top_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_third_floor_lobby", "Guild_Third_Floor_Lobby_Bottom_Marker")
  SV.partner.Spawn = 'Guild_Third_Floor_Lobby_Bottom_Marker_Partner'
end

function guild_storage_hallway.Right_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_storage_room", "Main_Entrance_Marker")
  SV.partner.Spawn = 'Default'
end

return guild_storage_hallway

