--[[
    init.lua
    Created: 06/10/2022 11:57:58
    Description: Autogenerated script file for the map illuminant_riverbed_entrance.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'
require 'ground.illuminant_riverbed_entrance.illuminant_riverbed_entrance_ch_2'

-- Package name
local illuminant_riverbed_entrance = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---illuminant_riverbed_entrance.Init
--Engine callback function
function illuminant_riverbed_entrance.Init(map, time)

	DEBUG.EnableDbgCoro()
	print('=>> Init_illuminant_riverbed_entrance <<=')
	MapStrings = COMMON.AutoLoadLocalizedStrings()
	COMMON.RespawnAllies()
	PartnerEssentials.InitializePartnerSpawn()
end

---illuminant_riverbed_entrance.Enter
--Engine callback function
function illuminant_riverbed_entrance.Enter(map, time)

	illuminant_riverbed_entrance.PlotScripting()

end

---illuminant_riverbed_entrance.Exit
--Engine callback function
function illuminant_riverbed_entrance.Exit(map, time)


end

---illuminant_riverbed_entrance.Update
--Engine callback function
function illuminant_riverbed_entrance.Update(map, time)


end

function illuminant_riverbed_entrance.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	illuminant_riverbed_entrance.PlotScripting()
end

function illuminant_riverbed_entrance.GameSave(map)
	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))
end


function illuminant_riverbed_entrance.PlotScripting()
	if SV.ChapterProgression.Chapter == 2 then 
		if not SV.Chapter2.EnteredRiver then
			illuminant_riverbed_entrance_ch_2.FirstAttemptCutscene()
		else 
			illuminant_riverbed_entrance_ch_2.SubsequentAttemptCutscene()
		end
	else
		GAME:FadeIn(20)
	end
end





function illuminant_riverbed_entrance.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
 end

return illuminant_riverbed_entrance


