--[[
    init.lua
    Created: 11/28/2023 00:57:31
    Description: Autogenerated script file for the map vast_steppe.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local vast_steppe = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---vast_steppe.Init(zone)
--Engine callback function
function vast_steppe.Init(zone)


end

---vast_steppe.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function vast_steppe.EnterSegment(zone, rescuing, segmentID, mapID)


end

---vast_steppe.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function vast_steppe.ExitSegment(zone, result, rescue, segmentID, mapID)
				
	GAME:EndDungeonRun(result, "master_zone", -1, 46, 0, true, true)
	GAME:EnterZone("master_zone", -1, 46, 0)


end

---vast_steppe.Rescued(zone, name, mail)
--Engine callback function
function vast_steppe.Rescued(zone, name, mail)


end

return vast_steppe

