--[[
    init.lua
    Created: 06/28/2021 23:00:22
    Description: Autogenerated script file for the map guild_bottom_left_bedroom.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'
require 'ground.guild_bottom_left_bedroom.guild_bottom_left_bedroom_ch_1'

local guild_bottom_left_bedroom = {}

--This is Breloom and Girafarig's bedroom.


local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_bottom_left_bedroom.Init
--Engine callback function
function guild_bottom_left_bedroom.Init(map)
	DEBUG.EnableDbgCoro()
	print('=>> Init_guild_bottom_left_bedroom<<=')
	MapStrings = COMMON.AutoLoadLocalizedStrings()
	COMMON.RespawnAllies()
	PartnerEssentials.InitializePartnerSpawn()

end

---guild_bottom_left_bedroom.Enter
--Engine callback function
function guild_bottom_left_bedroom.Enter(map)
	guild_bottom_left_bedroom.PlotScripting()
end

---guild_bottom_left_bedroom.Exit
--Engine callback function
function guild_bottom_left_bedroom.Exit(map)


end

---guild_bottom_left_bedroom.Update
--Engine callback function
function guild_bottom_left_bedroom.Update(map)


end

function guild_bottom_left_bedroom.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	guild_bottom_left_bedroom.PlotScripting()
end

function guild_bottom_left_bedroom.GameSave(map)
	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))
end

function guild_bottom_left_bedroom.PlotScripting()
	--plot scripting
	if SV.ChapterProgression.Chapter == 1 then
		guild_bottom_left_bedroom_ch_1.SetupGround()
	else
		GAME:FadeIn(20)
	end 
end
-------------------------------
-- Entities Callbacks
-------------------------------
function guild_bottom_left_bedroom.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
end

function guild_bottom_left_bedroom.Breloom_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("guild_bottom_left_bedroom_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Breloom_Action(...,...)"), chara, activator))
end

function guild_bottom_left_bedroom.Girafarig_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
 assert(pcall(load("guild_bottom_left_bedroom_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Girafarig_Action(...,...)"), chara, activator))
end



---------------------------
-- Map Transitions
---------------------------
function guild_bottom_left_bedroom.Bedroom_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_bedroom_hallway", "Guild_Bedroom_Hallway_Bottom_Left_Marker")
  SV.partner.Spawn = 'Guild_Bedroom_Hallway_Bottom_Left_Marker_Partner'
end

return guild_bottom_left_bedroom

