--[[
    init.lua
    Created: 07/15/2023 17:00:23
    Description: Autogenerated script file for the map apricorn_glade.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'
require 'ground.apricorn_glade.apricorn_glade_ch_4'

-- Package name
local apricorn_glade = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---apricorn_glade.Init(map)
--Engine callback function
function apricorn_glade.Init(map)

	DEBUG.EnableDbgCoro()
	print('=>> Init_apricorn_glade <<=')
	MapStrings = COMMON.AutoLoadLocalizedStrings()
	COMMON.RespawnAllies(true)
	PartnerEssentials.InitializePartnerSpawn()

end

---apricorn_glade.Enter(map)
--Engine callback function
function apricorn_glade.Enter(map)

  apricorn_glade.PlotScripting()

end

---apricorn_glade.Exit(map)
--Engine callback function
function apricorn_glade.Exit(map)


end

---apricorn_glade.Update(map)
--Engine callback function
function apricorn_glade.Update(map)


end

---apricorn_glade.GameSave(map)
--Engine callback function
function apricorn_glade.GameSave(map)

	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))

end

---apricorn_glade.GameLoad(map)
--Engine callback function
function apricorn_glade.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	apricorn_glade.PlotScripting()
end

function apricorn_glade.PlotScripting()
	if SV.ChapterProgression.Chapter == 4 then 
		if not SV.Chapter4.ReachedGlade then--first time reaching the glade
			apricorn_glade_ch_4.FirstArrivalCutscene()
		elseif not SV.Chapter4.FinishedGrove then
			apricorn_glade_ch_4.SubsequentArrivalCutscene()--came back after failing to get the apricorn
		else 
			--generic end
			apricorn_glade.GenericEnding() 
		end
	elseif SV.ChapterProgression.Chapter > 4 then 
		--generic end
		apricorn_glade.GenericEnding()
	else
		GAME:FadeIn(20)
	end
end 




--No cutscene to play, play a generic ending saying there's nothing here.
function apricorn_glade.GenericEnding()
	local hero = CH('PLAYER')
	local partner = CH('Teammate1')
	local team2 = CH('Teammate2')
	local team3 = CH('Teammate3')
	AI:DisableCharacterAI(partner)
	SOUND:StopBGM()
	GAME:WaitFrames(20)
	
	--the apricorn was picked
	GROUND:Hide('Apricorn_Scene')
	GROUND:TeleportTo(hero, 268, 368, Direction.Up)
	GROUND:TeleportTo(partner, 300, 368, Direction.Up)
	if team2 ~= nil then
		GROUND:TeleportTo(team2, 284, 400, Direction.Up)
	end
	if team3 ~= nil then
		GROUND:TeleportTo(team3, 316, 400, Direction.Up)
	end
	GAME:MoveCamera(292, 224, 1, false)

		
	GAME:CutsceneMode(true)
	UI:ResetSpeaker()
	UI:WaitShowTitle(GAME:GetCurrentGround().Name:ToLocal(), 20)
	GAME:WaitFrames(60)
	UI:WaitHideTitle(20)
	GAME:FadeIn(40)
	
	SOUND:PlayBGM('In The Depths of the Pit.ogg', true)
	
	local coro1 = TASK:BranchCoroutine(function() GROUND:MoveToPosition(partner, 300, 248, false, 1) end)
	local coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(10)
												  GROUND:MoveToPosition(hero, 268, 248, false, 1) end)
	local coro3 = TASK:BranchCoroutine(function() if team2 ~= nil then GAME:WaitFrames(14) GROUND:MoveToPosition(team2, 284, 280, false, 1) end end)
	local coro4 = TASK:BranchCoroutine(function() if team3 ~= nil then GAME:WaitFrames(18) GROUND:MoveToPosition(team3, 316, 280, false, 1) end end)
	
	TASK:JoinCoroutines({coro1, coro2, coro3, coro4})
	GAME:WaitFrames(10)	
	
	coro1 = TASK:BranchCoroutine(function() GeneralFunctions.LookAround(partner, 3, 4, false, false, true, Direction.Up) end)
	coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(10)
											GeneralFunctions.LookAround(hero, 3, 4, false, false, true, Direction.Up) end)
	coro3 = TASK:BranchCoroutine(function() if team2 ~= nil then GAME:WaitFrames(14) GeneralFunctions.LookAround(team2, 3, 4, false, false, true, Direction.Left) end end)										  
	coro4 = TASK:BranchCoroutine(function() if team3 ~= nil then GAME:WaitFrames(18) GeneralFunctions.LookAround(team3, 3, 4, false, false, true, Direction.Right) end end)										  
	TASK:JoinCoroutines({coro1, coro2, coro3, coro4})

	--temporary flags are set by the zone script rather than here.
	GAME:WaitFrames(20)
	UI:SetCenter(true)
	UI:WaitShowDialogue("There doesn't appear to be anything of interest here.")
	UI:WaitShowDialogue("It's impossible to go any further.[pause=0]\nIt's time to go back.")
	UI:SetCenter(false)
	SOUND:FadeOutBGM(60)
	GAME:FadeOut(false, 60)
	GAME:CutsceneMode(false)
	GAME:WaitFrames(20)
	
	SV.ApricornGrove.InDungeon = false
	--Go to second floor if mission was done, else, dinner room
	if SV.TemporaryFlags.MissionCompleted then
		GeneralFunctions.EndDungeonRun(RogueEssence.Data.GameProgress.ResultType.Cleared, "master_zone", -1, 22, 0, true, true)
	else
		GeneralFunctions.EndDungeonRun(RogueEssence.Data.GameProgress.ResultType.Cleared, "master_zone", -1, 6, 0, true, true)
	end
end

-------------------------------
-- Entities Callbacks
-------------------------------
function apricorn_glade.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
 end

function apricorn_glade.Teammate2_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function apricorn_glade.Teammate3_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

return apricorn_glade

