--[[
    init.lua
    Created: 07/15/2023 17:00:23
    Description: Autogenerated script file for the map apricorn_glade.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'
require 'ground.apricorn_glade.apricorn_glade_ch_4'

-- Package name
local apricorn_glade = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---apricorn_glade.Init(map)
--Engine callback function
function apricorn_glade.Init(map)

	DEBUG.EnableDbgCoro()
	print('=>> Init_apricorn_glade <<=')
	MapStrings = COMMON.AutoLoadLocalizedStrings()
	COMMON.RespawnAllies(true)
	PartnerEssentials.InitializePartnerSpawn()

end

---apricorn_glade.Enter(map)
--Engine callback function
function apricorn_glade.Enter(map)

  apricorn_glade.PlotScripting()

end

---apricorn_glade.Exit(map)
--Engine callback function
function apricorn_glade.Exit(map)


end

---apricorn_glade.Update(map)
--Engine callback function
function apricorn_glade.Update(map)


end

---apricorn_glade.GameSave(map)
--Engine callback function
function apricorn_glade.GameSave(map)

	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))

end

---apricorn_glade.GameLoad(map)
--Engine callback function
function apricorn_glade.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	apricorn_glade.PlotScripting()
end

function apricorn_glade.PlotScripting()
	if SV.ChapterProgression.Chapter == 4 then 
		if not SV.Chapter4.ReachedGlade then--first time reaching the glade
			apricorn_glade_ch_4.FirstArrivalCutscene()
		elseif not SV.Chapter4.FinishedGrove then
			apricorn_glade_ch_4.SubsequentArrivalCutscene()--came back after failing to get the apricorn
		else 
			--generic end
			apricorn_glade.GenericEnding()
		end
	else
		--generic end
		apricorn_glade.GenericEnding()
	end
end 




--No cutscene to play, play a generic ending saying there's nothing here.
function apricorn_glade.GenericEnding()
	GAME:FadeIn(20)
end

-------------------------------
-- Entities Callbacks
-------------------------------
function apricorn_glade.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
 end

function apricorn_glade.Teammate2_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function apricorn_glade.Teammate3_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

return apricorn_glade

