--[[
    init.lua
    Created: 07/15/2023 17:00:23
    Description: Autogenerated script file for the map apricorn_glade.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local apricorn_glade = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---apricorn_glade.Init(map)
--Engine callback function
function apricorn_glade.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---apricorn_glade.Enter(map)
--Engine callback function
function apricorn_glade.Enter(map)

  GAME:FadeIn(20)

end

---apricorn_glade.Exit(map)
--Engine callback function
function apricorn_glade.Exit(map)


end

---apricorn_glade.Update(map)
--Engine callback function
function apricorn_glade.Update(map)


end

---apricorn_glade.GameSave(map)
--Engine callback function
function apricorn_glade.GameSave(map)


end

---apricorn_glade.GameLoad(map)
--Engine callback function
function apricorn_glade.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return apricorn_glade

