--[[
    init.lua
    Created: 06/12/2023 20:58:54
    Description: Autogenerated script file for the map flying_maze.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local flying_maze = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---flying_maze.Init(zone)
--Engine callback function
function flying_maze.Init(zone)


end

---flying_maze.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function flying_maze.EnterSegment(zone, rescuing, segmentID, mapID)


end

---flying_maze.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function flying_maze.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---flying_maze.Rescued(zone, name, mail)
--Engine callback function
function flying_maze.Rescued(zone, name, mail)


end

return flying_maze

