--[[
    init.lua
    Created: 06/19/2023 11:32:20
    Description: Autogenerated script file for the map apricorn_grove.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local apricorn_grove = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---apricorn_grove.Init(zone)
--Engine callback function
function apricorn_grove.Init(zone)


end

---apricorn_grove.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function apricorn_grove.EnterSegment(zone, rescuing, segmentID, mapID)


end

---apricorn_grove.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function apricorn_grove.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---apricorn_grove.Rescued(zone, name, mail)
--Engine callback function
function apricorn_grove.Rescued(zone, name, mail)


end

return apricorn_grove

