--[[
    init.lua
    Created: 12/13/2023 17:56:20
    Description: Autogenerated script file for the map searing_tunnel_midpoint.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'
require 'ground.searing_tunnel_midpoint.searing_tunnel_midpoint_ch_5'

-- Package name
local searing_tunnel_midpoint = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---searing_tunnel_midpoint.Init(map)
--Engine callback function
function searing_tunnel_midpoint.Init(map)
  DEBUG.EnableDbgCoro()
  print('=>> Init_searing_tunnel_midpoint <<=')
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  COMMON.RespawnAllies(true)
  GROUND:AddMapStatus("steam")
  PartnerEssentials.InitializePartnerSpawn()

end

---searing_tunnel_midpoint.Enter(map)
--Engine callback function
function searing_tunnel_midpoint.Enter(map)

  searing_tunnel_midpoint.PlotScripting()

end

---searing_tunnel_midpoint.Exit(map)
--Engine callback function
function searing_tunnel_midpoint.Exit(map)


end

---searing_tunnel_midpoint.Update(map)
--Engine callback function
function searing_tunnel_midpoint.Update(map)


end

---searing_tunnel_midpoint.GameSave(map)
--Engine callback function
function searing_tunnel_midpoint.GameSave(map)

	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))

end

---searing_tunnel_midpoint.GameLoad(map)
--Engine callback function
function searing_tunnel_midpoint.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	searing_tunnel_midpoint.PlotScripting()
end

function searing_tunnel_midpoint.PlotScripting()
  if SV.ChapterProgression.Chapter == 5 then
	if not SV.Chapter5.PlayedMidpointIntro then
	  searing_tunnel_midpoint_ch_5.FirstArrival()
	elseif SV.SearingTunnel.DiedPastCheckpoint then 
		searing_tunnel_midpoint_ch_5.WipedCutscene()
	else 
		searing_tunnel_midpoint_ch_5.SetupGround()
	end
  else 
    GAME:FadeIn(20)
  end
end 


-------------------------------
-- Entities Callbacks
-------------------------------
function searing_tunnel_midpoint.North_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  UI:ResetSpeaker(false)
  UI:SetCenter(true)
  local hero = CH('PLAYER')
  local partner = CH('Teammate1')
  partner.IsInteracting = true
  GROUND:CharSetAnim(partner, 'None', true)
  GROUND:CharSetAnim(hero, 'None', true)		
  UI:ChoiceMenuYesNo("Would you like to continue?", true)
  UI:WaitForChoice()
  local yesnoResult = UI:ChoiceResult()
  UI:SetCenter(false)
  if yesnoResult then 
	if SV.ChapterProgression.Chapter == 5 then 
		searing_tunnel_midpoint_ch_5.ContinueScene()
	else
		--GROUND:Hide('North_Exit')
		--local coro1 = TASK:BranchCoroutine(function() GROUND:MoveInDirection(partner, Direction.Up, 90, false, 1) end)
		--local coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(10) GROUND:MoveInDirection(hero, Direction.Up, 90, false, 1) end)
		--local coro3 = TASK:BranchCoroutine(function() GAME:WaitFrames(20)
		--											  GAME:FadeOut(false, 60) end)
		--TASK:JoinCoroutines({coro1, coro2, coro3})
		GAME:FadeOut(false, 60)
		partner.IsInteracting = false
		GROUND:CharEndAnim(partner)
		GROUND:CharEndAnim(hero)	
		GAME:EnterDungeon("searing_tunnel", 1, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, true, false)
	end
  end
  partner.IsInteracting = false
  GROUND:CharEndAnim(partner)
  GROUND:CharEndAnim(hero)	
end


function searing_tunnel_midpoint.South_Exit_Touch(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  UI:ResetSpeaker(false)
  UI:SetCenter(true)
  local hero = CH('PLAYER')
  local partner = CH('Teammate1')
  local zone = _DATA.DataIndices[RogueEssence.Data.DataManager.DataType.Zone]:Get("searing_tunnel")
  partner.IsInteracting = true
  GROUND:CharSetAnim(partner, 'None', true)
  GROUND:CharSetAnim(hero, 'None', true)
  
	
  local exit_ground = ''
  --During Chapter 5, return to the dungeon entrance instead.
  if SV.ChapterProgression.Chapter == 5 then
	exit_ground = 'searing_tunnel_entrance'
	UI:ChoiceMenuYesNo("Would you like to return\nto " .. zone:GetColoredName() .. "'s entrance?", true)
  else
	exit_ground = 'guild_dining_room'
	if SV.TemporaryFlags.MissionCompleted then exit_ground = 'guild_second_floor' end 
	UI:ChoiceMenuYesNo("Would you like to return\nto Metano Town?", true)
  end
  UI:WaitForChoice()
  local yesnoResult = UI:ChoiceResult()
  UI:SetCenter(false)
  if yesnoResult then 
	--Clear thief flag when leaving the dungeon.		
	SV.adventure.Thief = false
	SOUND:FadeOutBGM(60)
	GAME:FadeOut(false, 60)
	partner.IsInteracting = false
	GROUND:CharEndAnim(partner)
	GROUND:CharEndAnim(hero)	
	GAME:WaitFrames(60)
	if SV.ChapterProgression.Chapter == 5 then 
		SV.Chapter5.PlayTempTunnelScene = true
		SV.Chapter5.TunnelLastExitReason = 'Retreated'
		SV.Chapter5.TunnelMidpointState = 'RepeatArrival'
	else 
		SV.TemporaryFlags.Dinnertime = true 
		SV.TemporaryFlags.Bedtime = true
		SV.TemporaryFlags.MorningWakeup = true 
		SV.TemporaryFlags.MorningAddress = true 
	end
	GAME:EnterGroundMap(exit_ground, "Main_Entrance_Marker")
  end
  partner.IsInteracting = false
  GROUND:CharEndAnim(partner)
  GROUND:CharEndAnim(hero)	
end

function searing_tunnel_midpoint.Kangaskhan_Rock_Action(obj, activator)
	GeneralFunctions.Kangashkhan_Rock_Interact(obj, activator)
end


function searing_tunnel_midpoint.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
 end

function searing_tunnel_midpoint.Teammate2_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  if SV.ChapterProgression.Chapter == 5 then--growlithe dialogue
	searing_tunnel_midpoint_ch_5.Growlithe_Action(chara, activator)
  else
	GeneralFunctions.GroundInteract(activator, chara)
  end
end

function searing_tunnel_midpoint.Teammate3_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  if SV.ChapterProgression.Chapter == 5 then--zigzagoon dialogue
	searing_tunnel_midpoint_ch_5.Growlithe_Action(chara, activator)
  else
	GeneralFunctions.GroundInteract(activator, chara)
  end
end

return searing_tunnel_midpoint

