--[[
    init.lua
    Created: 06/28/2021 23:00:22
    Description: Autogenerated script file for the map guild_top_right_bedroom.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'
require 'ground.guild_top_right_bedroom.guild_top_right_bedroom_ch_1'


-- Package name
local guild_top_right_bedroom = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_top_right_bedroom.Init
--Engine callback function
function guild_top_right_bedroom.Init(map)
	DEBUG.EnableDbgCoro()
	print('=>> Init_guild_top_right_bedroom<<=')
	MapStrings = COMMON.AutoLoadLocalizedStrings()
	COMMON.RespawnAllies()
	PartnerEssentials.InitializePartnerSpawn()

end

---guild_top_right_bedroom.Enter
--Engine callback function
function guild_top_right_bedroom.Enter(map)
	guild_top_right_bedroom.PlotScripting()
end

---guild_top_right_bedroom.Exit
--Engine callback function
function guild_top_right_bedroom.Exit(map)


end

---guild_top_right_bedroom.Update
--Engine callback function
function guild_top_right_bedroom.Update(map)


end


function guild_top_right_bedroom.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	guild_top_right_bedroom.PlotScripting()
end

function guild_top_right_bedroom.GameSave(map)
	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))
end

function guild_top_right_bedroom.PlotScripting()
	--plot scripting
	if SV.ChapterProgression.Chapter == 1 then
		if SV.Chapter1.MetSnubbull and SV.Chapter1.MetZigzagoon and SV.Chapter1.MetCranidosMareep and SV.Chapter1.MetBreloomGirafarig and SV.Chapter1.MetAudino then
			guild_top_right_bedroom_ch_1.SetupGround()--audino finishes all her chores by the time you finish talking to everyone and immediately passes out due to exhaustion
		else
			GAME:FadeIn(20)
		end
	else
		GAME:FadeIn(20)
	end
end


-------------------------------
-- Entities Callbacks
-------------------------------

function guild_top_right_bedroom.Audino_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  assert(pcall(load("guild_top_right_bedroom_ch_" .. tostring(SV.ChapterProgression.Chapter) .. ".Audino_Action(...,...)"), chara, activator))
end








function guild_top_right_bedroom.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
end

---------------------------
-- Map Transitions
---------------------------
function guild_top_right_bedroom.Bedroom_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_bedroom_hallway", "Guild_Bedroom_Hallway_Top_Right_Marker")
  SV.partner.Spawn = 'Guild_Bedroom_Hallway_Top_Right_Marker_Partner'
end

return guild_top_right_bedroom

