--[[
    init.lua
    Created: 12/17/2023 23:06:04
    Description: Autogenerated script file for the map vast_steppe_entrance.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'

-- Package name
local vast_steppe_entrance = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---vast_steppe_entrance.Init(map)
--Engine callback function
function vast_steppe_entrance.Init(map)
  DEBUG.EnableDbgCoro()
  print('=>> Init_vast_steppe_entrance <<=')
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  COMMON.RespawnAllies()
  PartnerEssentials.InitializePartnerSpawn()

end

---vast_steppe_entrance.Enter(map)
--Engine callback function
function vast_steppe_entrance.Enter(map)

  vast_steppe_entrance.PlotScripting()

end

---vast_steppe_entrance.Exit(map)
--Engine callback function
function vast_steppe_entrance.Exit(map)


end

---vast_steppe_entrance.Update(map)
--Engine callback function
function vast_steppe_entrance.Update(map)


end

---vast_steppe_entrance.GameSave(map)
--Engine callback function
function vast_steppe_entrance.GameSave(map)

	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))

end

---vast_steppe_entrance.GameLoad(map)
--Engine callback function
function vast_steppe_entrance.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	vast_steppe_entrance.PlotScripting()
end

function vast_steppe_entrance.PlotScripting()
  GAME:FadeIn(20)
end 


-------------------------------
-- Entities Callbacks
-------------------------------
function vast_steppe_entrance.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
 end

function vast_steppe_entrance.Teammate2_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

function vast_steppe_entrance.Teammate3_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  COMMON.GroundInteract(activator, chara, true)
end

return vast_steppe_entrance

