--[[
    init.lua
    Created: 06/28/2021 22:41:56
    Description: Autogenerated script file for the map guild_bedroom_hallway.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'

-- Package name
local guild_bedroom_hallway = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_bedroom_hallway.Init
--Engine callback function
function guild_bedroom_hallway.Init(map)
	DEBUG.EnableDbgCoro()
	print('=>> Init_guild_bedroom_hallway <<=')
	MapStrings = COMMON.AutoLoadLocalizedStrings()
	COMMON.RespawnAllies()
	PartnerEssentials.InitializePartnerSpawn()

end

---guild_bedroom_hallway.Enter
--Engine callback function
function guild_bedroom_hallway.Enter(map)
	guild_bedroom_hallway.PlotScripting()
end

---guild_bedroom_hallway.Exit
--Engine callback function
function guild_bedroom_hallway.Exit(map)


end

---guild_bedroom_hallway.Update
--Engine callback function
function guild_bedroom_hallway.Update(map)


end

-------------------------------
-- Entities Callbacks
-------------------------------
function guild_bedroom_hallway.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))
end

function guild_bedroom_hallway.GameLoad(map)
	PartnerEssentials.LoadGamePartnerPosition(CH('Teammate1'))
	guild_bedroom_hallway.PlotScripting()
end

function guild_bedroom_hallway.GameSave(map)
	PartnerEssentials.SaveGamePartnerPosition(CH('Teammate1'))
end

function guild_bedroom_hallway.PlotScripting()
	GAME:FadeIn(20)
end

---------------------------
-- Map Transitions
---------------------------
function guild_bedroom_hallway.Top_Left_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_top_left_bedroom", "Main_Entrance_Marker")
  SV.partner.Spawn = 'Default'
end

function guild_bedroom_hallway.Top_Right_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_top_right_bedroom", "Main_Entrance_Marker")
  SV.partner.Spawn = 'Default'
end

function guild_bedroom_hallway.Bottom_Left_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_bottom_left_bedroom", "Main_Entrance_Marker")
  SV.partner.Spawn = 'Default'
end

function guild_bedroom_hallway.Bottom_Right_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_bottom_right_bedroom", "Main_Entrance_Marker")
  SV.partner.Spawn = 'Default'
end

function guild_bedroom_hallway.Right_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_heros_room", "Main_Entrance_Marker")
  SV.partner.Spawn = 'Default'
end

function guild_bedroom_hallway.Left_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_third_floor_lobby", "Guild_Third_Floor_Lobby_Right_Marker")
  SV.partner.Spawn = 'Guild_Third_Floor_Lobby_Right_Marker_Partner'
end


return guild_bedroom_hallway

