--[[
    init.lua
    Created: 06/12/2023 20:41:47
    Description: Autogenerated script file for the map rock_maze.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local rock_maze = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---rock_maze.Init(zone)
--Engine callback function
function rock_maze.Init(zone)


end

---rock_maze.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function rock_maze.EnterSegment(zone, rescuing, segmentID, mapID)


end

---rock_maze.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function rock_maze.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---rock_maze.Rescued(zone, name, mail)
--Engine callback function
function rock_maze.Rescued(zone, name, mail)


end

return rock_maze

