--[[
    init.lua
    Created: 03/21/2021 22:07:39
    Description: Autogenerated script file for the map metano_cave.
]]--
-- Commonly included lua functions and data
require 'common'
require 'PartnerEssentials'
require 'GeneralFunctions'

-- Package name
local metano_cave = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---metano_cave.Init
--Engine callback function
function metano_cave.Init(map, time)

	DEBUG.EnableDbgCoro()
	print('=>> Init_metano_cave <<=')
	MapStrings = COMMON.AutoLoadLocalizedStrings()
	COMMON.RespawnAllies()

	GROUND:AddMapStatus(50)--darkness


	--set partner to follow us, disable his collision
	local chara = CH('Teammate1')
	AI:SetCharacterAI(chara, "ai.ground_partner", CH('PLAYER'), chara.Position)
	chara.CollisionDisabled = true

end

---metano_cave.Enter
--Engine callback function
function metano_cave.Enter(map, time)
	DEBUG.EnableDbgCoro()
	print('Enter_metano_cave')
	GAME:FadeIn(20)
	UI:ResetSpeaker()

end

---metano_cave.Exit
--Engine callback function
function metano_cave.Exit(map, time)


end

---metano_cave.Update
--Engine callback function
function metano_cave.Update(map, time)


end

-------------------------------
-- Map Transitions
-------------------------------

function metano_cave.Cave_Entrance_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("metano_town", "Cave_Entrance_Marker")
  SV.partner.Spawn = 'Cave_Entrance_Marker_Partner'
end



------------------
--NPCS 
----------------
function metano_cave.Teammate1_Action(chara, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PartnerEssentials.GetPartnerDialogue(CH('Teammate1'))end

return metano_cave

